### ISSUE TITLE
How to use this library with multiple Grove MP3 and Arduino Mega / Due?

### ISSUE THREAD

**Issue by sulram** [Seeed-Studio/Grove_Serial_MP3_Player_V2.0#1]
Hello there

I'm trying to use this library with Arduino Master and Due, but they don't support SoftwareSerial library. How can I connect them throught the available Serial1, Serial2 and Serial3?

Thanks in advance!

**Comment by sulram** [comment]
I'm passing the serial port as parameters, by changing the functions to something like:

```
void SelectPlayerDevice(USARTClass serial, uint8_t device)
{
    serial.write(0x7E);
    serial.write(0xFF);
    serial.write(0x06);
    serial.write(0x09);
    serial.write(uint8_t(0x00));
    serial.write(uint8_t(0x00));
    serial.write(device);
    serial.write(0xEF);
    delay(200);
}
```

**Comment by sulram** [comment]
Hello guys,

I just forked this library and created new files for using mutiple instances:
https://github.com/sulram/Grove_Serial_MP3_Player_V2.0/commit/35219dcc7d19604482783a295189700a99b6626b

To work with this new class, you need to pass the SoftwareSerial instance as first argument of the methods.

I can do a PULL REQUEST if you want.

Thanks

**Comment by mike2nl** [comment]
@sulram 
Hi,
i have seen some things in the serial.write structure. It looks very familiear
to the DFRobot Mini MP3 Player. I had written last year a driver for that one
for tasmota here on github. iTead wireless devices which can switch on/off
things and can use sensors.

Now what i have seen is that the command structure is 100% the same and i had
manganed to add a USB device to that mini mp3 player. So with a command i
can switch the source.

Further when i take a look at the bottom of the PCB from the Grove MP2 Player V2
i see the text for USB Data + and -. In the schema you can see it too on pin 20 and 21.

In the datasheet for the chip i have found the command to change the device:
0x09 - Choose specified device to play music file on it - 00 02(microSD)
---
00 02(microSD) default
00 01 or 00 03 must be the USB device (USB Stick)

Have orderd now a Grove MP3 player V2 and will test it.
Possible we both can work together. 

BTW: i like your idea of multiple players! Have forked that part.

![knipsel](https://user-images.githubusercontent.com/5562918/53923119-6158b480-4077-11e9-9281-c873caeee21a.PNG)

**Comment by Pillar1989** [comment]
8916fd02ba31a26104c6b26578be4d3b8d4183fb
